language: node_js
node_js: '8'
cache: yarn
install: npm install
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: npm
  email: julien.croain@gmail.com
  skip_cleanup: true
  api_key:
    secure: $NPM_SECURE_TOKEN
  on:
    tags: true
    repo: JulienCroain/vue-tag-input
    branch: master
